package components;

/**
 *
 * @author Miketo
 */
public class BtnCafetera extends javax.swing.JButton {

    /**
     * Creates new form BtnCafetera
     */
    public BtnCafetera() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Buchanan", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setBorderPainted(false);
        setFocusPainted(false);
        setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
